return {
	talon_ack = {
		acceleration = 0.12,
		brakerate = 1.14,
		buildcostenergy = 3050,
		buildcostmetal = 485,
		builddistance = 225,
		builder = true,
		buildpic = "talon_ack.png",
		buildtime = 4650
		canguard = true,
		canmove = true,
		canpatrol = true,
		canreclamate = 1,
		canstop = 1,
		category = "ALL CONSTR LARGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL NOTWEAPON SURFACE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "33 36 35",
		collisionvolumetype = "Box",
		corpse = "1_dead",
		defaultmissiontype = "Standby",
		description = "Advanced Tech Level 1",
		energymake = 14,
		energystorage = 100,
		energyuse = 0,
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 25,
		maneuverleashlength = 640,
		mass = 485,
		maxdamage = 1250,
		maxslope = 20,
		maxvelocity = 1.75,
		maxwaterdepth = 25,
		metalmake = 0.14,
		metalstorage = 100,
		mobilestandorders = 1,
		movementclass = "KBOT2",
		name = "Advanced Construction Kbot",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "talon_ack",
		radardistance = 50,
		radaremitheight = 25,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 325,
		standingmoveorder = 1,
		steeringmode = 1,
		terraformspeed = 1220,
		turninplace = 1,
		turninplaceanglelimit = 60,
		turninplacespeedlimit = 0.759,
		turnrate = 990,
		unitname = "talon_ack",
		upright = true,
		workertime = 200
		buildoptions = {
			[1] = "talon_solar",
			[2] = "talon_win",
			[3] = "talon_gen",
			[4] = "talon_geo",
			[5] = "talon_mex1",
			[6] = "talon_makr",
			[7] = "talon_nanotc",
			[8] = "talon_clone_lab",
			[9] = "talon_alab",
			[10] = "talon_avp",
			[11] = "talon_aap",
			[12] = "talon_ahp",
			[13] = "armeyes", 
			[14] = "talon_fort",
			[15] = "talon_arad",
			[16] = "talon_obelisk",
			[17] = "talon_vhlt",
			[18] = "talon_vhlt",
			[19] = "talon_sprinkler ",
			[20] = "talon_slinger",
			[21] = "talon_blt",
			[22] = "talon_rl",
			[23] = "talon_cir",
			[24] = "talon_ptr",
			[25] = "talon_asy",
			[26] = "talon_psycher",
		},
		customparams = {
			buildpic = "talon_ack.png",
			faction = "arm",
		},
		featuredefs = {
			["1_dead"] = {
				blocking = true,
				collisionvolumeoffsets = "1.64561462402 6.61621093734e-06 -1.44562530518",
				collisionvolumescales = "29.6044616699 29.4648132324 28.049697876",
				collisionvolumetype = "Box",
				damage = 2306,
				description = "Advanced Construction Kbot Wreckage",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				metal = 1105,
				object = "talon_ack_DEAD",
				reclaimable = true,
			},
		},
		nanocolor = {
			[1] = 0.216,
			[2] = 0.616,
			[3] = 0.216,
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
	},
}
